controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: false

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

# Mecanum drive controller parameters
mecanum_drive_controller:
  ros__parameters:
    wheel_names:
      - wheel1_joint
      - wheel2_joint
      - wheel3_joint

    robot_radius: 0.25
    wheel_radius: 0.05
    gamma: 30.0 # angle between body fixed y axis and the normal of wheel3

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    odom_numeric_integration_method: runge_kutta2

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 1.0
    use_stamped_vel: false


    joints:
      - name: wheel1_joint
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]
      - name: wheel2_joint
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]
      - name: wheel3_joint
        command_interfaces: [velocity]
        state_interfaces: [position, velocity]

